from dataclasses import dataclass
from datetime import datetime


@dataclass
class Finding:
    """
    Information discovered from a source.

    source_url is mandatory because provenance must be preserved
    from the moment the Finding enters ContentForge.
    """

    title: str
    content: str
    source_url: str
    source_type: str
    fetched_at: datetime
    source_id: str = ""


@dataclass
class DraftVariant:
    """
    One candidate generated by the X writer.

    The LLM produces multiple variants with different angles,
    not merely different wording.
    """

    id: str
    post: str
    thread: list[str]
    first_reply: str | None
    media_suggestion: str | None
    alt_text: str | None
    char_count: int
    reply_surface: str


@dataclass
class Draft:
    """
    Complete X generation result.

    One Finding can produce multiple candidate variants.
    """

    status: str
    archetype: str
    variants: list[DraftVariant]
    source_url: str
    rejected_angle: str | None = None
    notes: str | None = None

@dataclass
class Claim:
    """
    One factual claim extracted from a draft.

    The claim keeps the complete verification trail:
    claim -> source -> evidence -> verdict -> model.
    """

    claim_text: str
    source_url: str
    evidence_text: str = ""
    evidence_location: str = ""
    verdict: str = "NO_EVIDENCE"
    judged_by: str = ""

    @property
    def is_supported(self) -> bool:
        """
        True only when the claim has been explicitly
        judged as supported.
        """

        return self.verdict == "SUPPORTED"


@dataclass
class VerificationResult:
    """
    Complete verification result for a draft.
    """

    status: str
    claims: list[Claim]
    blocked_reasons: list[str] | None = None

    @property
    def is_verified(self) -> bool:
        """
        A draft is verified only if every claim
        is supported.
        """

        return (
            self.status == "VERIFIED"
            and all(
                claim.is_supported
                for claim in self.claims
            )
        )